- name: Create /tmp/kubeadm-ha directory
  file:
    path: /tmp/kubeadm-ha
    state: directory    

- name: Copy kubeadm init config
  template:
    src: kubeadm.yml 
    dest: /tmp/kubeadm-ha/kubeadm.yml
