apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.grafana.service.name }}
  labels:
    app: grafana
    component: core
spec:
  type: NodePort
  selector:
    app: grafana
    component: core
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    nodePort: 30000
